### ISSUE TITLE
Missing gateway trades

### ISSUE THREAD

**Issue by LovelessTie** [DarkPacks/SkyFactory-5#22]
Not sure if is on purpose but some Gateways don't appear in the villager trades

White:
Energetic Sheep
Horned Sheep
Pink:
Shrimp
Brown:
Fluid Cow
Gray:
Illusioner
Green:
Lobber Zombie
Blue:
Lobber Drowned

**Comment by calog3no** [comment]
@LovelessTie  just fyi you need read the template for the proper way to submit the bug. It has a pretty good explanation. If you remove certain parts of the template, the bot will auto close bug submissions.

**Comment by LovelessTie** [comment]
It was a accidental submit I was going do it properly. I was just tiding up my notes when my attention staved cat decided to jump up on my desk lay over my  keyboard and mouse.
