### ISSUE TITLE
Missing gateway trades

### ISSUE THREAD

**Issue by LovelessTie** [DarkPacks/SkyFactory-5#23]
## Bug Description

Had some trouble attempting to get Gateways from villager trades
White:
Energetic Sheep
Horned Sheep
Pink:
Shrimp
Brown:
Fluid Cow
Gray:
Illusioner
Green:
Lobber Zombie
Blue:
Lobber Drowned

### Did this behavior use to work in the previous version?

Don't think so only noticed it trying to finish off the advancements and witnessed MisterWiggly having problems getting the same ones from villagers, so i looked at the villager trade script and saw them missing.

## Steps to Reproduce (for bugs)

None

1.
2.
3.

## Logs

- Client/Server Log:None
- Crash Log:None

## World Information

- Modpack Version world created in: SkyFactory 5 Preview Build 1
- Additional Content Installed: None

## Client Information

- Modpack Version:SkyFactory 5 Preview Build 4
- Java Version: Curseforge Default
- Launcher Used:Curseforge
- Memory Allocated: 7200MB
- Server/LAN/Single Player:Single
- Optifine Installed:No
- Shaders Enabled:No

**Comment by Darkosto** [comment]
Energetic Sheep and Fluid Cows are intentionally left out but all the others should be there. I'll get these added ASAP, thank you very much for letting me know!!
