### ISSUE TITLE
Cannot change spawner by right clicking with trophy

### ISSUE THREAD

**Issue by calog3no** [DarkPacks/SkyFactory-5#25]
## Bug Description

Attempted to change a spawner with a trophy, and spawner does not change mob in spawner. Attempted to change spawner with modifications applied, and also tried to change spawner with no modification applied. Neither spawner would change mob spawn. 

### Did this behavior use to work in the previous version? yes

Patreon preview build 4

## Steps to Reproduce (for bugs)

1.Place down spawner
2.right click with trophy, only places trophy does not change mob type in spawner
3.shift right click spawner with trophy, only places trophy but does not change mob in spawner

## Logs

- Client/Server Log:n/a
- Crash Log:n/a

## World Information

- Modpack Version world created in:Patreon build 5
- Additional Content Installed:none

## Client Information

- Modpack Version:Patreon preview build 5
- Java Version:1.17
- Launcher Used:Prism
- Memory Allocated:12g
- Server/LAN/Single Player:Single Player
- Optifine Installed:no
- Shaders Enabled:no

**Comment by Darkosto** [comment]
Fixed in dev
