### ISSUE TITLE
When pressing ESC, some items can show color

### ISSUE THREAD

**Issue by DuskO7** [DarkPacks/SkyFactory-5#3]
## Bug Description

Whenever pressing ESC, certain items can show all the colors, even when other colors arent unlocked yet.

### Did this behavior use to work in the previous version?

uhhhh... first version

## Steps to Reproduce (for bugs)

1. open new world
2. place down green campfire with green unlocked
3. press esc when next to it

## Logs

- Client/Server Log:
- Crash Log:

## World Information

- Modpack Version world created in: 1.0
- Additional Content Installed:

## Client Information

- Modpack Version: 1.0
- Java Version: I honestly dont know 😭 
- Launcher Used: Curseforge
- Memory Allocated: >16 GB
- Server/LAN/Single Player: Singleplayer
- Optifine Installed: No
- Shaders Installed: No

**Comment by DuskO7** [comment]
![image](https://github.com/user-attachments/assets/4c636a40-debc-4030-95b9-ca3e543fb0e9)

Image

**Comment by DuskO7** [comment]
Same for crafting stations, ect, seems to be tons of items/blocks that are modded.

**Comment by Darkosto** [comment]
This is due to how the shader works especially when the esc menu has a shader over top of that. There's not really a ton we can do to get it perfect so we try to get it as close as possible. I'll check in with the shader dev and see if there's any more room to work with this, thanks for the report!

**Comment by Darkosto** [comment]
Just got a new build from the dev of Color Stages and it looks like he was able to catch some of stray colors not being disabled. This should be fixed now. I'll close the issue and let me know in a new issue if it persists after the next update.
