### ISSUE TITLE
Wooden Hopper randomly stops working until you break it and replace it.

### ISSUE THREAD

**Issue by kiaen1** [DarkPacks/SkyFactory-5#5]
Not a bug, figured out the issue myself. It's occasionally grabbing the dirt when I try to collect it.

**Comment by Darkosto** [comment]
Sorry, my power was out for 5 days so I haven't been able to catch up. This one is good though? No issue?

**Comment by kiaen1** [comment]
> Sorry, my power was out for 5 days so I haven't been able to catch up. This one is good though? No issue?

No worries!
Yes everything is good, I just wasn't catching the fact it was stealing the dirt sometimes. If anything I would consider this a a mod issue(The fact that it doesn't properly prioritize an inventory placed above the hopper)
