### ISSUE TITLE
Occultism crusher spirit not dropping crushed ores

### ISSUE THREAD

**Issue by calog3no** [DarkPacks/SkyFactory-5#7]
## Bug Description

Summoned an Occultism Foliot crusher spirit and gave them ores. The spirit crushed the ores, but the drop was a missing texture block not crushed ore. It did produce 2 blocks for each ore, so the drop amount is correct.

### Did this behavior use to work in the previous version?

Using Patreon Test ver 1.0

## Steps to Reproduce (for bugs)

1.Summon crusher spirit
2.Give ores to spirit
3.Spirit crushed ores, but drops missing texture blocks

## Logs

- Client/Server Log: https://gist.github.com/e8cd6fc1e4438c8d82d361270041a563.git
- Crash Log: No crash log

## World Information

- Modpack Version world created in: Patreon Test ver 1.0
- Additional Content Installed: none

## Client Information

- Modpack Version: Patreon Test ver 1.0
- Java Version: Java 17
- Launcher Used:Prism Launcher
- Memory Allocated: 12 g
- Server/LAN/Single Player: Single Player
- Optifine Installed: no
- Shaders Enabled: no
![2024-11-21_10 17 55](https://github.com/user-attachments/assets/64f9c38c-b1df-40d2-be30-d8b96fecbe9c)
[
![2024-11-22_11 58 36](https://github.com/user-attachments/assets/0aedc346-6697-44b2-83a0-e34e2d2cce26)

**Comment by Darkosto** [comment]
This has been fixed and will be out for the next Patreon update. Thank you very much!
