### ISSUE TITLE
Crusher spirit from Occultism still missing crushing recipe in Patreon build 2

### ISSUE THREAD

**Issue by calog3no** [DarkPacks/SkyFactory-5#8]
## Bug Description

Started new world with most current patreon build 2. Checked crusher recipes in jei and found the recipes are still showing missing item tags
### Did this behavior use to work in the previous version?

No

## Steps to Reproduce (for bugs)

1.Checked recipe in jei
2.Recipe for crusher spirit output shows missing item blocks
3.confirmed missing recipe

## Logs

https://gist.github.com/calog3no/57af25b2906a079a0b96e6b06c86c5b1
- Client/Server Log: Single player world
- Crash Log: client didn't crash

## World Information

- Modpack Version world created in: Patreon build 2 test ver
- Additional Content Installed:none

## Client Information

- Modpack Version: Patreon Build 2 test ver
- Java Version: 17
- Launcher Used: Prism
- Memory Allocated: 12g
- Server/LAN/Single Player: Single player
- Optifine Installed: no
- Shaders Enabled: no
![2024-11-26_11 29 13](https://github.com/user-attachments/assets/1c1364a5-d50a-4dcf-bb29-058c5d6f0940)

**Comment by kiaen1** [comment]
Hey! Just a heads up, this is a leftover from the fact that you made the world in patreon pack 1(Henceforth known as world 1).

If you create a world in patreon pack 2, and load it, after loading you should then be able to load world 1 again, and it should have the proper recipes.

Actually, I see you said you made it in pack 2, are you positive?

**Comment by calog3no** [comment]
When I made the instance for the new Patreon 2 dev I stated over with a new world. I did not use any previous saves from the first instance.

**Comment by calog3no** [comment]
I'm positive that this is the new instance because I got the advancement notification that I had unlocked all the colors even though I did had not created all the colored saplings yet, and I know that is a change from Patreon Dev 1.

**Comment by calog3no** [comment]
ok so I had this issue in another pack I was testing and /reload will fix the issue once kube js reloads all the way. Here is an updated screen shot after /reload command

![2024-11-26_15 20 13](https://github.com/user-attachments/assets/1900ea06-c393-4fd2-a277-cc03b9083e29)

**Comment by kiaen1** [comment]
That's fair! I also want to point out that loading a "New" save and then the old save only works until you close the game, Same thing with /reload. I have to do that each time I start the game.

**Comment by calog3no** [comment]
Yeah, every time you launch the pack once you log into the save you have to run  /reload command. The issue I believe is Kube js is overwriting the recipe when the instance first loads.

**Comment by Darkosto** [comment]
This shouldn't have anything to do with KubeJS as it's not touching recipes or tags, I'll take a look and see what's going on

**Comment by Darkosto** [comment]
Fixed in Patreon build 3 and will be released on Monday
